app:
    version: 1.0.0

auth0:
  issuer: https://<Your Auth0 domain>
  apiAudience: http://localhost:8080


spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
          jdbc:
            lob:
              non_contextual_creation: true

logging:
    level:
      org: WARN